### ISSUE TITLE
OutPut Path

### ISSUE THREAD

**Issue by sophiewalten** [Vinyzu/MjolnirAiO#11]
Hi sorry. I'm kind of new to this and I don't know where else to ask you this. I'm not experiencing any errors but i'm experiencing a problem going to the final step, where the website asks me at the end of each thing for an "output path". I was wondering what I should put there..! I saw in your video that what you have put is a "temp.txt" file, however, I unfortunately do not have that. should I download it (in case the answer is yes, could you tell me where?), or do I have other alternatives? I would appreciate very much if you could solve this doubt, by far what I have seen this looks very good and promising so even though I have not used and enjoyed this to its fullest experience I want to congratulate you for your great work!

**Comment by Vinyzu** [comment]
Yo,
first of all i appreciate that you like my work this much (even tho i have to note that this tool is bout 4 months old so is probably outdated a lot).
You can put any .txt file path in that input. For example, create a output.txt on your desktop and copy its filepath (you can right-click on the file to copy it).
Then, you can easily input this path into the tool and it will save your accounts in this file.

**Comment by sophiewalten** [comment]
Alright, thank you so much for replying! :)
